[package]
name = "utils"
version = "0.1.0"
edition = "2024"
description = "A collection of algorithms used during the IFT2425 course at Université de Montréal."
authors = ["etiennecollin <collin.etienne.contact@gmail.com>"]
license = "MIT"

[dependencies]
nalgebra = "0.33.2"
tabled = "0.18.0"
